name: netflix
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.6
  flutter_svg: ^1.0.3
  equatable: ^2.0.5
  http: ^0.13.5
  dartz: ^0.10.1
  get: ^4.6.5
  youtube_player_flutter: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/icons/
    - assets/videos/
  fonts:
    - family: Netflix Sans
      fonts:
        - asset: assets/fonts/NetflixSans-Light.otf
        - asset: assets/fonts/NetflixSans-Regular.otf
        - asset: assets/fonts/NetflixSans-Medium.otf
        - asset: assets/fonts/NetflixSans-Bold.otf
